name: Deploy to ec2

#triggering the workflow
on:
   push:
     branches:
       - cicd

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run a linux command 
        run: ls -la     