name: Deploy to ec2

#triggering the workflow
on:
   push:
     branches:
       - cicd

jobs:
  deploy1:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run a linux command 
        run: ls -la   

  deploy2:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run a linux command 
        run: cat index.html

  deploy3:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run a linux command 
        run: cat style.css   